### ISSUE TITLE
problems on speech sdk for ios

### ISSUE THREAD

**Issue by halissonvit** [Microsoft/ProjectOxford-ClientSDK#10]
Hi,

I apologize for posting it here, but I couldn't really find an issue tracker for the ios SDK. So, just checking if maybe you guys can help with this, or at least provide me a link where I can find help.

I am trying to use the ios SDK, but for some reason, the flow doesn't work as it is supposed to.

I am using the MicrophoneClientWithIntent, but for some reason the method onIntentReceived is not being called as it should.

Is this a known issue? Any ideas how to workaround it?

onFinalReponseReceived is called, but there is no information about the intent at that point.

Thanks,

**Comment by jasonvomsft** [comment]
Hi halissonvit, did you set the 'isIntent' flag in the ViewController.mm and do you have a valid subscription for getting intent?

**Comment by halissonvit** [comment]
@jasonvomsft Thank you for the answer.

Yes I did, and yes, I have a valid subscription.
It is working just fine on Android 5.x.

I have debugged, and it uses the correct MicrophoneClientWithIntent, and even call the correct methods... But it doesn't call the onIntentReceived as it should.

**Comment by halissonvit** [comment]
@jasonvomsft any news on this ?

**Comment by jasonvomsft** [comment]
can you provide client logs?  i'm not able to reproduce the problem.

**Comment by lightfrenzy** [comment]
@halissonvit - are you still experiencing this issue? If so, can you send over client logs? If not, I'll close out the issue

**Comment by halissonvit** [comment]
Sorry, we are not using this on our iOS app anymore due to this issue...

I believe you can close the issue, if nobody else is facing it.
