### ISSUE TITLE
Speech Recognition hangs with wave files recorded on iOS

### ISSUE THREAD

**Issue by SaqibS** [Microsoft/ProjectOxford-ClientSDK#12]
I am successfully using speech recognition using the data client (with and without intent) from a C# service.

However, if the wave file was recorded on iOS using the AVAudioRecorder class, none of the callbacks get called.

The difference between these wave files and others is that they have a FLLR chunk in the header, between the regular FMT and data chunks which are commonly found in wave files. If I remove the FLLR chunk, everything works fine. However, the service should probably cope with this natively.

**Comment by jasonvomsft** [comment]
Hi SaqibS, can you provide the audio file you are using?

**Comment by SaqibS** [comment]
Find the audio file [here](https://onedrive.live.com/redir?resid=26C87562A0A39909!174743&authkey=!AEcPBhdTo387Bk0&ithint=file%2cwav), and a Python script for stripping out the FLLR chunk [here](https://onedrive.live.com/redir?resid=26C87562A0A39909!174742&authkey=!AC-zdyhbQ9YUEuE&ithint=file%2cpy).

**Comment by jasonvomsft** [comment]
This will be addressed in the next client refresh.

**Comment by haluky** [comment]
Hey Jason,
what about xamarin?





















 


  tr.linkedin.com/in/mustafahalukyilmaz/

Date: Tue, 16 Feb 2016 09:36:15 -0800

**Comment by SaqibS** [comment]
Any update on this? Still get the same problem.

**Comment by jasonvomsft** [comment]
The updated SDK available today addresses this issue.  Please give it a try.

**Comment by lightfrenzy** [comment]
Closing out the issue. If the issue still repros, please re-open!
