### ISSUE TITLE
Generic exception thrown when keys have expired

### ISSUE THREAD

**Issue by SaqibS** [Microsoft/ProjectOxford-ClientSDK#13]
I have an Azure service which makes use of multiple Project Oxford APIs, and overnight calls to each of the services started failing.

I looked through the logs, and found that the client libraries for both Vision and Face were throwing a System.Exception, with message: "Transport error".

Eventually, I found that invoking the APIs using rest directly, I got a useful message back, saying that the keys had expired. Why this happened is a separate issue, along with why I didn't get any emails to say that the keys were going to expire (they still show as active on the website). But that's all separate - this bug relates to the fact that the client libraries shouldn't just throw a generic Exception with such a vague message. The message returned by the rest API should be wrapped in the client-specific exception.

**Comment by yungshinlintw** [comment]
Hi SaqibS,

Thanks a lot for reporting this! We will address this for the next update.

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-Vision-Windows#4

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-Face-Windows#4
