### ISSUE TITLE
AndroidSDK for Speech fails on Nexus 5 with Android 6.0.1.

### ISSUE THREAD

**Issue by ykakihara** [Microsoft/ProjectOxford-ClientSDK#14]
I'm trying to use the speech-to-text functionality through mic and experiencing issues. Would be super grateful to get some help/pointers here.

The sample app works when built but I am unable to get it work in my own prototype. The very same prototype works on Nexus 5 with 5.1.1.

I'm using Gradle with the usual ```compile 'com.microsoft.projectoxford:speechrecognition:0.5.2'``` clause with ```libandroid_platform.so``` copied from SDK into my project's ```jniLibs/armeabi```. Upon calling MicrophoneRecognitionClient.startMicAndRecognition() I get the following error.

```
01-07 22:49:23.519 30128-30128/my.app.package I/NLPLAT: Initialize@163 Using local IHost
01-07 22:49:23.521 30128-30128/my.app.package I/NLPLAT: InitializeFileSystem@20 originating error 0x80070057 from InitializeFileSystem 20
01-07 22:49:23.526 30128-30128/my.app.package I/NLPLAT: Initialize@522 ServiceUri: https://websockets.platform.bing.com/ws/speech/recognize
01-07 22:49:24.080 30128-30128/my.app.package I/NLPLAT: OnPreConnect@182 originating error 0x80070057 from OnPreConnect 182
01-07 22:49:24.080 30128-30128/my.app.package I/NLPLAT: BeginRequest@147 originating error 0x80070057 from BeginRequest 147
01-07 22:49:24.081 30128-30128/my.app.package I/NLPLAT: CloseInternal@111 
01-07 22:49:24.082 30128-1067/my.app.package I/NLPLAT: Receive@491 originating error 0x8000ffff from Receive 491
01-07 22:49:24.082 30128-1067/my.app.package I/NLPLAT: Worker@709 originating error 0x8000ffff from Worker 709
01-07 22:49:24.082 30128-1067/my.app.package I/NLPLAT: CloseInternal@111 
01-07 22:49:24.511 30128-30128/my.app.package I/NLPLAT: BeginRequest@149 Refreshing token S
01-07 22:49:24.511 30128-30128/my.app.package I/NLPLAT: OpenApplicationFile@52 originating error 0x80070057 from OpenApplicationFile 52
01-07 22:49:24.511 30128-30128/my.app.package I/NLPLAT: AppFileToString@136 originating error 0x80070057 from AppFileToString 136
01-07 22:49:24.511 30128-30128/my.app.package I/NLPLAT: InitializeRenderer@103 originating error 0x80070057 from InitializeRenderer 103
01-07 22:49:24.511 30128-30128/my.app.package I/NLPLAT: Initialize@749 Initializing Audio Services
01-07 22:49:24.512 30128-30128/my.app.package W/AudioRecord: AUDIO_INPUT_FLAG_FAST denied by client; transfer 1, track 16000 Hz, primary 48000 Hz
01-07 22:49:24.514 30128-30128/my.app.package E/AudioRecord: AudioFlinger could not create record track, status: -1
01-07 22:49:24.516 30128-30128/my.app.package E/libOpenSLES: android_audioRecorder_realize(0xae3bba00) error creating AudioRecord object; status -1
01-07 22:49:24.516 30128-30128/my.app.package W/libOpenSLES: Leaving Object::Realize (SL_RESULT_CONTENT_UNSUPPORTED)
01-07 22:49:24.516 30128-30128/my.app.package I/NLPLAT: Initialize@47 originating error 0x8000ffff from Initialize 47
01-07 22:49:24.516 30128-30128/my.app.package E/NLPLAT: native error -1910439934
```

It looks like the library failed to gain access to the audio source, in this case the microphone... Any ideas on how this might be resolved?

**Comment by jasonvomsft** [comment]
have you enabled the RECORD_AUDIO permission in your manifest file?

**Comment by ykakihara** [comment]
@jasonvomsft yes i have. but now you've mentioned permission, i just recalled that Android 6.0 introduced explicit permissions. shall see if that solves the problem...

**Comment by lightfrenzy** [comment]
@ykakihara -- did this solve the issue?

**Comment by ykakihara** [comment]
@lightfrenzy have't got around to it yet, will get to it as soon as i can

**Comment by awayo** [comment]
The problem is here:

W/AudioRecord: AUDIO_INPUT_FLAG_FAST denied by client; transfer 1, track 16000 Hz, primary 48000 Hz

The library asks for an audio source that is incompatible with the hardware. They must check what modes are present and use one of them. 

So now, some devices works and others don't

**Comment by seblogapps** [comment]
I had the same problem, when set in build.gradle
       targetSdkVersion 22
and finally the code runs. You can try the same to see if it helps

**Comment by seblogapps** [comment]
It's definetly problem because you don't require run time permission needed for Android 6.0, 
hopefully the Project Oxford sdk itself should have the code to request permission , but until then you've to add the code by yourself.
You can check how to do it here:
https://developer.android.com/training/permissions/requesting.html

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-Speech-STT-Android#2

**Comment by margaretmz** [comment]
Issue was moved to Microsoft/Cognitive-Speech-STT-Android#2
