### ISSUE TITLE
Not able to detect the emotion 

### ISSUE THREAD

**Issue by rajat007** [Microsoft/ProjectOxford-ClientSDK#16]
While I am loading the image the then it is not able to detect any face for the purpose of detection of emotion, even it is not working for the default

**Comment by cthrash** [comment]
Can you double-check that your subscription key is correct?  This page lists your keys: https://www.projectoxford.ai/subscription

**Comment by lightfrenzy** [comment]
@rajat007 -- did cthrash's comment fix your issue?

**Comment by lightfrenzy** [comment]
Closing out. Please reopen if you continue to have an issue after trying cThrash's suggsetion
