### ISSUE TITLE
SpeechClient.dll does not work with Windows Server 2012 R2 Datacenter

### ISSUE THREAD

**Issue by parijat1209** [Microsoft/ProjectOxford-ClientSDK#19]
I have a ASP.NET deployed on Windows Server 2012. We use HTML5 Speech API to capture user's microphone. These microphone samples are sent to the server using sockets. On the server, we forward this samples to Project Oxford servers using SpeechClient.dll. 

This dll works on Windows 10 and on Azure WebSite. Exception which I get is: 
System.IO.FileNotFoundException: Could not load file or assembly 'SpeechClient.dll' or one of its dependencies. The specified module could not be found.

Please Help.

**Comment by jasonvomsft** [comment]
Make sure you have the Visual C++ Redistributable Packages for Visual Studio 2013 installed.

**Comment by lightfrenzy** [comment]
@parijat1209 -- did Jasonvomsft's tip solve the issue?

**Comment by lightfrenzy** [comment]
Closing out the issue since we haven't seen a response

**Comment by ohoncharuk** [comment]
It still doesn't work for me even with Visual C++ Redistributable Packages for Visual Studio 2013 installed.

**Comment by jasonvomsft** [comment]
@ohoncharuk Make sure you have the MediFoundation Windows feature enabled and that you have the audio service running.  You can refer to https://technet.microsoft.com/en-us/library/dn609826(v=ws.11).aspx for details on installing.

**Comment by innomanik** [comment]
I have got the same problem with my windows server 2019 datacenter on AWS, I have installed Visual C++ Redistributable Packages for Visual Studio 2013 and have also enabled the Media Foundation Windows feature. Still getting this - 'SpeechClient.DLL' or one of its dependencies. The specified module could not be found.
