### ISSUE TITLE
SpeechSDK for OSX

### ISSUE THREAD

**Issue by chipallen2** [Microsoft/ProjectOxford-ClientSDK#20]
I couldn't find a github project for the iOS Speech Recognition SDK so I'm posting here.

I attempted to use the iOS Speech Recognition SDK in an OSX project and got a linker error when it was compiling. Is there a way to get the SpeechSDK.Framework to work with OSX? Or is there an OSX sdk planned for speech recognition?

**Comment by jasonvomsft** [comment]
We are actively working on providing an OSX version of the framework soon.

**Comment by jasonvomsft** [comment]
The OSX SpeechSDK framework is now available under https://github.com/Microsoft/ProjectOxford-ClientSDK/tree/master/Speech/SpeechToText/iOS/MacOSX.
