### ISSUE TITLE
Speech sdks cannot connect to websocket server

### ISSUE THREAD

**Issue by boxfish** [Microsoft/ProjectOxford-ClientSDK#22]
Both the iOS and Android app hang up at "OnHeadersAvailable@104 Auth token status: 200" after calling `createMicrophoneClient` method. The same code worked fine one week ago on both platforms.

**The log from iOS console:**

Initialize@522 ServiceUri: https://websockets.platform.bing.com/ws/speech/recognizeInitialize@589 Application Name: com.Microsoft.SpeechRecognitionServerExampleOnPreConnect@182 originating error 0x80070057 from OnPreConnect 182BeginRequest@147 originating error 0x80070057 from BeginRequest 147CloseInternal@111 CloseInternal@111 BeginRequest@149 Refreshing token /token/issueTokenAppFileToString@136 originating error 0x80004005 from AppFileToString 136InitializeRenderer@103 originating error 0x80004005 from InitializeRenderer 103Initialize@749 Initializing Audio ServicesLoadController@1567 Initializing Speech ServicesCUClient@104 Constructing CU client 0x0x7fcb79e23700RefreshState@133 Unable to get the max traffic limit from registry.RefreshState@143 Unable to get the current traffic counter from registry.ReadProperty@1041 originating error 0x8000ffff from ReadProperty 1041GetIdentityPropertyValue@235 GetIdentityPropertyValue 3GetUserAgent@255 Useragent Value iOS Assistant (iOS; 9.2;Phone;ProcessName/AppName=com.Microsoft.SpeechRecognitionServerExample;DeviceType=Near)CreateIHttpSession@98 Created WinHttp session for use by WebSocketChannel hr = (0x0)Init@126 Initializing web socket channel to endpoint https://websockets.platform.bing.com/ws/speech/recognizeInitiateHandshake@630 Initiating websocket connection. m_connection=0x0 host=websockets.platform.bing.com port=443OnHeadersAvailable@104 Auth token status: 200

**The console log from Android:**

02-16 18:12:47.502 12524-12524/? D/dalvikvm: Late-enabling CheckJNI
02-16 18:12:47.619 12524-12524/com.sample.test D/dalvikvm: Trying to load lib /data/data/com.sample.test/lib/libandroid_platform.so 0x41055dc0
02-16 18:12:47.650 12524-12524/com.sample.test D/dalvikvm: Added shared lib /data/data/com.sample.test/lib/libandroid_platform.so 0x41055dc0
02-16 18:12:47.650 12524-12524/com.sample.test D/dalvikvm: No JNI_OnLoad found in /data/data/com.sample.test/lib/libandroid_platform.so 0x41055dc0, skipping init
02-16 18:12:47.650 12524-12524/com.sample.test I/NLPLAT: Initialize@163 Using local IHost
02-16 18:12:47.658 12524-12524/com.sample.test I/NLPLAT: InitializeFileSystem@20 originating error 0x80070057 from InitializeFileSystem 20
02-16 18:12:47.666 12524-12524/com.sample.test I/NLPLAT: Initialize@522 ServiceUri: https://websockets.platform.bing.com/ws/speech/recognize
02-16 18:12:47.806 12524-12524/com.sample.test I/NLPLAT: OnPreConnect@182 originating error 0x80070057 from OnPreConnect 182
02-16 18:12:47.806 12524-12524/com.sample.test I/NLPLAT: BeginRequest@147 originating error 0x80070057 from BeginRequest 147
02-16 18:12:47.814 12524-12524/com.sample.test I/NLPLAT: CloseInternal@111 
02-16 18:12:47.814 12524-12565/com.sample.test I/NLPLAT: Receive@491 originating error 0x8000ffff from Receive 491
02-16 18:12:47.814 12524-12565/com.sample.test I/NLPLAT: Worker@709 originating error 0x8000ffff from Worker 709
02-16 18:12:47.814 12524-12565/com.sample.test I/NLPLAT: CloseInternal@111 
02-16 18:12:47.908 12524-12524/com.sample.test I/NLPLAT: BeginRequest@149 Refreshing token S
02-16 18:12:47.908 12524-12524/com.sample.test I/NLPLAT: OpenApplicationFile@52 originating error 0x80070057 from OpenApplicationFile 52
02-16 18:12:47.908 12524-12524/com.sample.test I/NLPLAT: AppFileToString@136 originating error 0x80070057 from AppFileToString 136
02-16 18:12:47.908 12524-12524/com.sample.test I/NLPLAT: InitializeRenderer@103 originating error 0x80070057 from InitializeRenderer 103
02-16 18:12:47.908 12524-12524/com.sample.test I/NLPLAT: Initialize@749 Initializing Audio Services
02-16 18:12:47.908 12524-12524/com.sample.test E/ASFDummyExtractor: isASFParserAvailable 
02-16 18:12:47.908 12524-12524/com.sample.test W/ASFDummyExtractor: ASF parser is not available
02-16 18:12:47.916 12524-12524/com.sample.test W/libOpenSLES: class OutputMix interface 0 requested but unavailable MPH=43
02-16 18:12:47.924 12524-12524/com.sample.test I/NLPLAT: Load@205 Opening VAD 'raw/vcd/common/grammar/Date.0409.vad.xml'
02-16 18:12:47.924 12524-12524/com.sample.test I/NLPLAT: OpenApplicationFile@52 originating error 0x80070057 from OpenApplicationFile 52
02-16 18:12:47.924 12524-12524/com.sample.test I/NLPLAT: AppFileToString@136 originating error 0x80070057 from AppFileToString 136
02-16 18:12:47.924 12524-12524/com.sample.test I/NLPLAT: Load@207 originating error 0x80070057 from Load 207
02-16 18:12:47.924 12524-12524/com.sample.test I/NLPLAT: SetLocale@104 originating error 0x80070057 from SetLocale 104
02-16 18:12:47.924 12524-12524/com.sample.test I/NLPLAT: LoadController@1570 Initializing Speech Services
02-16 18:12:47.924 12524-12524/com.sample.test I/NLPLAT: CUClient@104 Constructing CU client 0x0x198c558
02-16 18:12:47.924 12524-12524/com.sample.test I/NLPLAT: RefreshState@133 Unable to get the max traffic limit from registry.
02-16 18:12:47.924 12524-12524/com.sample.test I/NLPLAT: RefreshState@143 Unable to get the current traffic counter from registry.
02-16 18:12:47.924 12524-12524/com.sample.test I/NLPLAT: ReadProperty@1041 originating error 0x8000ffff from ReadProperty 1041
02-16 18:12:47.924 12524-12524/com.sample.test I/NLPLAT: GetIdentityPropertyValue@235 GetIdentityPropertyValue 3
02-16 18:12:47.924 12524-12524/com.sample.test I/NLPLAT: GetUserAgent@255 Useragent Value Android Assistant (Android; Unknown;Unknown;ProcessName/AppName=Unknown;DeviceType=Near)
02-16 18:12:47.924 12524-12524/com.sample.test I/NLPLAT: CreateIHttpSession@98 Created WinHttp session for use by WebSocketChannel hr = (0x0)
02-16 18:12:47.924 12524-12524/com.sample.test I/NLPLAT: Init@126 Initializing web socket channel to endpoint https://websockets.platform.bing.com/ws/speech/recognize
02-16 18:12:47.924 12524-12524/com.sample.test I/NLPLAT: InitiateHandshake@630 Initiating websocket connection. m_connection=0x0 host=websockets.platform.bing.com port=443
02-16 18:12:47.971 12524-12571/com.sample.test I/NLPLAT: OnHeadersAvailable@104 Auth token status: 200

**Comment by jasonvomsft** [comment]
Does the iOS/Android samples work?

**Comment by boxfish** [comment]
@jasonvomsft Nope, the samples stuck at the same place.

**Comment by jasonvomsft** [comment]
What is the network quality during this time?

**Comment by boxfish** [comment]
Yeah, it turns out to be the company network problem. For some reason they
started to block websocket traffic recently. I have no problem connecting
from my home network. Thanks for help and feel free to close this!

**Comment by lightfrenzy** [comment]
Thanks for following up @boxfish. Closing out the issue!
