### ISSUE TITLE
How to call emotion api in PHP?

### ISSUE THREAD

**Issue by professorchwu** [Microsoft/ProjectOxford-ClientSDK#32]
I try to call Emotion API via PHP program. However, it can't work. How to fix my program?

My program is showed below.

How to call JSON format in request body ?

where can I download the reuqest2.php?

Thank you

------------------------------------------------------------------------------------------------------------------------------

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>無標題文件</title>
</head>

<body>
<?php
// This sample uses the Apache HTTP client from HTTP Components (http://hc.apache.org/httpcomponents-client-ga/)
require_once 'HTTP/Request2.php';

$request = new Http_Request2('https://api.projectoxford.ai/emotion/v1.0/recognize');
$url = $request->getUrl();

$headers = array(
    // Request headers
    'Content-Type' => 'application/json',
    'Ocp-Apim-Subscription-Key' => 'XXXXXX',

);

$request->setHeader($headers);

$parameters = array(
    // Request parameters
    'faceRectangles' => '',
);

//left,top,width,height”

$url->setQueryVariables($parameters);

$request->setMethod(HTTP_Request2::METHOD_POST);

// Request body

$request->setBody('http://chwu.weebly.com/uploads/2/9/3/6/29369481/1402061272.jpg');
  

try
{
    $response = $request->send();
    echo $response->getBody();
}
catch (HttpException $ex)
{
    echo $ex;
}

?>
</body>
</html>

**Comment by cthrash** [comment]
Please refer to the answer in the MSDN forum [here](https://social.msdn.microsoft.com/Forums/azure/en-US/3baeb8d0-c767-40c9-9f88-529370a6b21e/emotion-api-via-php?forum=mlapi)
