### ISSUE TITLE
 Person group ID is invalid.

### ISSUE THREAD

**Issue by roblatour** [Microsoft/ProjectOxford-ClientSDK#35]
the following code (vb.net vs 2015) 

```
 Dim PersonGroupId As String = "Justme"
 Await IFaceServiceClient.CreatePersonGroupAsync(PersonGroupId, "Just_me")
```
generates an exception, which reads:
 BadArgument
 Person group ID is invalid.

Prior to this i am able to run the line:
`Dim faceRects As FaceRectangle() = Await UploadAndDetectFaces(CurrentFilePath)`
with results as expected.

**Comment by cthrash** [comment]
In very small print, the [spec](https://dev.projectoxford.ai/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395244) stipulates that uppercase letters are not permitted.

> personGroupId as a string. The valid characters include numbers, English letters in lower case, '-' and '_'. The maximum length of the personGroupId is 64.

**Comment by halukmy** [comment]
Hello, 
sadly couldn't success
can you share code samples?
plus on xamarin components store, there is only surf guy sample,
dialpad?




















 


  tr.linkedin.com/in/mustafahalukyilmaz/

Date: Mon, 14 Mar 2016 12:19:54 -0700

**Comment by cthrash** [comment]
I'm afraid I don't understand the question.  Are you having issues specifically with PersonGroups?  If not, I encourage you to open a new issue so as to reduce confusion.

**Comment by roblatour** [comment]
Thank you ctrash, I missed where it said upper case letters are not permitted.  Changed to all lower case and it worked like a charm.  Crazy.  Thanks, Rob
