### ISSUE TITLE
How to submit my local images to API?

### ISSUE THREAD

**Issue by yeucommmotaomo** [Microsoft/ProjectOxford-ClientSDK#37]
I can run an example through URL image with my own request code(not SDKs).

Is there any way that I can submit my local images?

**Comment by cthrash** [comment]
You can stream the image file as the body of the HTTP request.  Be sure to use ``Content-Type: application/octet-stream`` as one of the HTTP headers.

**Comment by yeucommmotaomo** [comment]
Thank you so much. I solve this using the following codes:

 File file = new File("/***.jpg");
 FileEntity reqEntity = new FileEntity(file);
 request.setEntity(reqEntity);
