### ISSUE TITLE
ARM IoT Build

### ISSUE THREAD

**Issue by JanWerder** [Microsoft/ProjectOxford-ClientSDK#38]
Hello,

I'm trying to use the Speech SDK with the Windows IoT Platform, but unfortunately only a x64 and x86 build of the libraries are provided. Would it be possible to provide an ARM Build for the Windows IoT Platform?

**Comment by jasonvomsft** [comment]
There are no immediate plans on releasing an ARM flavor of the Speech SDK currently.  For IOT, I would suggest using the REST APIs for Speech as an alternate solution.

Details on the REST API can be found here 
https://www.microsoft.com/cognitive-services/en-us/speech-api/documentation/overview.

**Comment by JanWerder** [comment]
Okay, would it be possible to add that to a future release plan? I mean IoT is an official Microsoft product, so I would kind of expect the Speech SDK to support it.

The alternative solution is fine, I guess, but it creates way more initial work to get started. Is there any sample project for using the REST API or would I have to roll my own?

**Comment by lightfrenzy** [comment]
@JanWerder, we're using UserVoice to track feature requests for APIs so we can aggregate all data in one place. The best next step is to create a suggestion there so other developers can upvote it and you can be kept notified when we have an update. The forum can be found at https://cognitive.uservoice.com.

The link that Jason sent has some good details and samples on how to use the REST API, and you can also check out this doc: https://www.microsoft.com/cognitive-services/en-us/speech-api/documentation/API-Reference-REST/BingVoiceRecognition.
