### ISSUE TITLE
VS EmotionAPI_WPF_Samples issue 

### ISSUE THREAD

**Issue by LuisFolgadoFerreira** [Microsoft/ProjectOxford-ClientSDK#39]
![err](https://cloud.githubusercontent.com/assets/18197952/14189938/efd3cf88-f787-11e5-9cb5-aabb2b457790.JPG)

Im trying EmotionAPI_WPF_Samples in VS15 

I need some advice about this main error.

**Comment by chsienki** [comment]
Hi @LuisFolgadoFerreira. 

Have you tried building the solution at this point? When first opening the project Visual Studio often incorrectly reports these errors as the matching Xaml code files aren't generated until you first build.

If you've built and you're still seeing errors, could you paste the build output from the output window?

Thanks

**Comment by LuisFolgadoFerreira** [comment]
Hi chsienki!

Nice tip. Worked.

Just cant see, with the rigth reg. keys, any results with several images (even with the example).

Thanks
