### ISSUE TITLE
Error executing POST request 

### ISSUE THREAD

**Issue by Juude** [Microsoft/ProjectOxford-ClientSDK#4]
give me the error
Error: Error executing POST request！
Received error code:401

**Comment by yungshinlintw** [comment]
Hi Juude,

Thanks for the feedback. Can you please give more details about what API (face, speech, etc) that you are using, or what sample gave you the error? Given more details, we will look into it. Sorry for the inconvenience.

Thanks,
Yung-Shin

**Comment by dlfu** [comment]
hi @Juude ! 
is it possible that you did not provide the subscription key? usually 401 error is a permission issue

**Comment by yungshinlintw** [comment]
Please also note that subscription key is per service (face, speech, etc). Here is the updated page to get subscription key for free use: http://projectoxford.ai/subscription

**Comment by lightfrenzy** [comment]
Bump to @Juude, are you still having an issue with the API? Let us know so we can file a bug report or close out this issue.

Thanks!

**Comment by IgnacioHR** [comment]
Line 496 in code is misleading. It should read:
Authentication auth = new Authentication("Your ClientId goes here", "Your Primary Key for Speech API goes here");

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-Speech-TTS#2

**Comment by RanchoDbest** [comment]
@Juude , Have u solved that issue regarding Error executing post request! ?
