### ISSUE TITLE
Android Speech API LongDictation dutch language returns without translation

### ISSUE THREAD

**Issue by Marc1510** [Microsoft/ProjectOxford-ClientSDK#43]
I'm using the [Speech to text Android SDK](https://github.com/Microsoft/ProjectOxford-ClientSDK/tree/master/Speech/SpeechToText/Android) with the sample application. However as the documentation says it should support the language dutch. So I changed the `getDefaultLocale()` to return 'nl-NL'. When the language code has changed the complete recognition stops. On the screen is visible that it did start with LongDictation recognition but the next message is *** Final n-BEST Results ***' without any result. The ShortDictation does work with the dutch language for some reason.

**Comment by domtallo** [comment]
On the web version of the library the input is all lowercase, like "nl-nl". Maybe here it's also is the case. Have you tried that?

**Comment by Marc1510** [comment]
@domtallo I have tried that but it also returns immediately. However for short dictation it does work.

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-Speech-STT-Android#3
