### ISSUE TITLE
emotion analysis on local image with python

### ISSUE THREAD

**Issue by Wheele9** [Microsoft/ProjectOxford-ClientSDK#45]
Can you provide a python example to show how to use the  face/emotion API on local images?
I was unable to make it work. With images from internet the notebooks work well :)
Maybe you can make a python3 version of your notebooks too, just change the dict.iteritems to dict.items and add some parenthesis to the prints.

**Comment by cristiancanton** [comment]
Some Jupyter notebooks ([Face](https://github.com/Microsoft/ProjectOxford-ClientSDK/blob/master/Face/Python/Jupyter%20Notebook/Face%20Detection%20Example.ipynb), [Emotion](https://github.com/Microsoft/ProjectOxford-ClientSDK/blob/master/Emotion/Python/Jupyter%20Notebook/Emotion%20Analysis%20Example.ipynb) and [Computer Vision](https://github.com/Microsoft/ProjectOxford-ClientSDK/blob/master/Vision/Python/Jupyter%20Notebook/Computer%20Vision%20API%20Example.ipynb) APIs) have been updated showing how to use images stored in disk. 

Essentially, you read the raw image into a variable and then pass it to the service. You notify the API that the input is a raw blob as shown in the examples.

**Comment by Wheele9** [comment]
Awesome, thanks!
