### ISSUE TITLE
[Vision API] CancelationToken for Async calls.

### ISSUE THREAD

**Issue by snap608** [Microsoft/ProjectOxford-ClientSDK#46]
Since the VisionServiceClient (C#) have no timeout we should be able to pass a CancelationToken or set a timeout for all calls to the API via the VisionServiceClient.

_PS: Because of the downtime today (6.apr 2016) our integration encountered a hang._

**Comment by cthrash** [comment]
This will be considered in a future release.  The request will have timed out eventually on the client side(100 seconds).

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-Vision-Windows#2
