### ISSUE TITLE
LinguisticsClient json parse error

### ISSUE THREAD

**Issue by mehmetilker** [Microsoft/ProjectOxford-ClientSDK#47]
When  I run LinguisticsClient sample I got exception as follows:
Unexpected character encountered while parsing value: [. Path '[0].result', line 1, position 64.

It returns proper json but when it try deserialize it throw exception. Json looks valid.

`return JsonConvert.DeserializeObject<TResponse>(responseContent, settings);`
I tried to change settings but did not worked as well.

`[{
		"analyzerId" : "4fa79af1-f22c-408d-98bb-b7d7aeef7f04",
		"result" : [["NNP", "TO", "NNP", "NNP", "NNP", "."]]
	}, {
		"analyzerId" : "22a6b758-420f-4745-8a3c-46835a67c0d2",
		"result" : ["(TOP (INTJ (UH Welcome) (PP (TO to) (NP (NNP Microsoft) (NNP Linguistic) (NNP Analysis))) (. !)))"]
	}, {
		"analyzerId" : "08ea174b-bfdb-4e64-987e-602f85da7f72",
		"result" : [{
				"Len" : 41,
				"Offset" : 0,
				"Tokens" : [{
						"Len" : 7,
						"NormalizedToken" : "Welcome",
						"Offset" : 0,
						"RawToken" : "Welcome"
					}, {
						"Len" : 2,
						"NormalizedToken" : "to",
						"Offset" : 8,
						"RawToken" : "to"
					}, {
						"Len" : 9,
						"NormalizedToken" : "Microsoft",
						"Offset" : 11,
						"RawToken" : "Microsoft"
					}, {
						"Len" : 10,
						"NormalizedToken" : "Linguistic",
						"Offset" : 21,
						"RawToken" : "Linguistic"
					}, {
						"Len" : 8,
						"NormalizedToken" : "Analysis",
						"Offset" : 32,
						"RawToken" : "Analysis"
					}, {
						"Len" : 1,
						"NormalizedToken" : "!",
						"Offset" : 40,
						"RawToken" : "!"
					}
				]
			}
		]
	}
]
`

**Comment by chrisquirk** [comment]
Ah sorry about that -- I believe it's an issue with one of the types. I'm working on it and should have a fix for you soon.

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-LinguisticAnalysis-Windows#3
