### ISSUE TITLE
Some errors when running the Linguistic.Sample.sln 

### ISSUE THREAD

**Issue by qindaying** [Microsoft/ProjectOxford-ClientSDK#49]
Hi,
I found a difficulty when I tried to run the sample in LinguisticAnalysis by following 'Getting started'.  I pasted my subscription key in the Program.cs (replace the "Your subscription key") and built the solution successfully, but I cannot ran the example successfully. Some errors appeared are as follows:

1. The error poped when I opened the solution
TF400324: Team Foundation services are not available from server http://vstfsng01:8080/tfs/cig.
Technical information (for administrator):
  The remote name could not be resolved: 'vstfsng01'
The active solution has been temporarily disconnected from source control because the server is unavailable.  To attempt to reconnect to source control, close and then re-open the solution when the server is available.  If you want to connect this solution to another server, use the Change Source Control dialog.
The mappings for the solution could not be found.
The mappings for the solution could not be found.
The active solution has been temporarily disconnected from source control because the server is unavailable.  To attempt to reconnect to source control, close and then re-open the solution when the server is available.  If you want to connect this solution to another server, use the Change Source Control dialog.

2. The errors after I pressed F5
'Microsoft.ProjectOxford.Linguistics.Sample.vshost.exe' (CLR v4.0.30319: Microsoft.ProjectOxford.Linguistics.Sample.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Microsoft.ProjectOxford.Linguistics.Sample.vshost.exe' (CLR v4.0.30319: Microsoft.ProjectOxford.Linguistics.Sample.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Microsoft.ProjectOxford.Linguistics.Sample.vshost.exe' (CLR v4.0.30319: Microsoft.ProjectOxford.Linguistics.Sample.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Microsoft.ProjectOxford.Linguistics.Sample.vshost.exe' (CLR v4.0.30319: Microsoft.ProjectOxford.Linguistics.Sample.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Diagnostics.Debug\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Diagnostics.Debug.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'Newtonsoft.Json.JsonReaderException' in Newtonsoft.Json.dll
Exception thrown: 'Newtonsoft.Json.JsonReaderException' in mscorlib.dll
Exception thrown: 'System.AggregateException' in mscorlib.dll
Exception thrown: 'System.Exception' in Microsoft.ProjectOxford.Linguistics.Sample.exe

Thank you very much! :)

**Comment by cthrash** [comment]
@chrisquirk is working on a fix.  The first issue you can safely ignore.  The second issue you can work around by changing the type of ``Microsoft.ProjectOxford.Linguistics.Contract.AnalyzeTextResult.Result`` from ``string`` to ``object``.

**Comment by qindaying** [comment]
Thanks again! I have run it successfully! Another question is how to call this program for my own use (I mean the interface of this toolkit) because I need to complete a project as final exam about a human-computer interaction program. Do I have to use C# language to call it? I have little knowledge about C#  .  (T-T) 

Looking forward to your reply and thanks a lot for taking up your time!!

**Comment by cthrash** [comment]
The C# library is merely a thin wrapper for the REST API.  You can find some sample code for invoking the API using other languages in the [API documentation](https://dev.projectoxford.ai/docs/services/56ea598f778daf01942505ff/operations/56ea5a1cca73071fd4b102bb).

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-LinguisticAnalysis-Windows#2
