### ISSUE TITLE
Universal app support

### ISSUE THREAD

**Issue by balassy** [Microsoft/ProjectOxford-ClientSDK#5]
Installing the Emotion NuGet package into a Windows 10 universal application fails with the following error:

```
Installing Microsoft.ProjectOxford.Emotion 1.0.0.1.
Microsoft.ProjectOxford.Emotion 1.0.0.1 is not compatible with UAP,Version=v10.0.
Some packages are not compatible with UAP,Version=v10.0.
Microsoft.ProjectOxford.Emotion 1.0.0.1 is not compatible with UAP,Version=v10.0 (win10-arm).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm).
Microsoft.ProjectOxford.Emotion 1.0.0.1 is not compatible with UAP,Version=v10.0 (win10-arm-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
Microsoft.ProjectOxford.Emotion 1.0.0.1 is not compatible with UAP,Version=v10.0 (win10-x86).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86).
Microsoft.ProjectOxford.Emotion 1.0.0.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
Microsoft.ProjectOxford.Emotion 1.0.0.1 is not compatible with UAP,Version=v10.0 (win10-x64).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64).
Microsoft.ProjectOxford.Emotion 1.0.0.1 is not compatible with UAP,Version=v10.0 (win10-x64-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
```

Any plans to support universal apps in the near future?

Thanks for all the hard work you do, it is awesome!

György

**Comment by yungshinlintw** [comment]
Hi György,

Thanks a lot for your kind words. Project Oxford team really appreciate your feedback!
Unfortunately, Universal Apps is not supported at this moment by the client library, but we are evaluating this. Will let you know as soon as we have a decision on this. Thanks!

**Comment by balassy** [comment]
Hello Yung-Shin,

As a try I created a new Portable Library project, added a reference to the Newtonsoft.Json NuGet package, and copied all files from the EmotionClient project in the SDK. I could compile everything successfully, the only minor issue was the `[Serializable]` attribute on the `ClientException` class.

So it seems to me that the only work to do here is change the project type, or is there any other issue I didn't catch yet?

Thank you.
György

**Comment by yungshinlintw** [comment]
Hi György,
We are looking into this as well, and we will support UWP for emotion recognition. The dev from Emotion team is working on this right now, and will let you know when we are ready to release it.

And I think that you are right that this is mainly project type change + the serializable fix. We will also ensure that this can be easily used in nuget as well. 

Thanks again for your feedback.

**Comment by yungshinlintw** [comment]
cthrash has a fix and we will publish an update on emotion nugget package to support UWP soon. And your description about the fix is correct. Thanks.

**Comment by balassy** [comment]
Thanks Yung-Shin, thank you Chris.

**Comment by didaskein** [comment]
Hi, 
Do you have any news about this. 

We would like to test TTS on an UniversallApp. Could you share a beta version of the SDK ?
The other way is to use the REST API but in the sample you don't manage the microphone : https://oxfordportal.blob.core.windows.net/speech/doc/recognition/Program.cs

Do you have a sample with the call to REST api and the microphone ?

Thank you in advance,

**Comment by haluky** [comment]
Thanks but i do use api.ai
i prefer vision and emotion api
with best






















 



 


  | Haluk YILMAZ | +90 507 044 3 888 | FrontEnd Developer & IT Specialist |  
  Windows Phone HQ: http://goo.gl/RpG9Q    Android HQ: http://goo.gl/BJGQO
tr.linkedin.com/in/mustafahalukyilmaz/

Date: Tue, 15 Dec 2015 02:57:26 -0800

**Comment by lightfrenzy** [comment]
Hi @didaskein 
We don't have a TTS universal app SDK at this time, but we'll take this request into consideration. @jasonvomsft as fyi

**Comment by cthrash** [comment]
Folks, a UWP should be supported in the latest push.  We will be following up with an updated NuGet package soon too.  Thanks for you patience.

**Comment by afourney** [comment]
Are there any plans to support speech to text with universal apps? The Windows.Media.SpeechRecognition libraries aren't quite the same, and don't appear to support LUIS intents (as far as I can tell).

**Comment by lightfrenzy** [comment]
Closing out the issue since the Emotion update has been pushed to both GitHub and Nuget.

@afourney, no updates to share about Oxford's Speech-to-text with universal apps but letting @jasonvomsft know as fyi

**Comment by balassy** [comment]
Thank you very much!

**Comment by afourney** [comment]
@lightfrenzy @jasonvomsft Thanks! I forgot to mention -- I'm in 99/3243 in case you want to chat abou this more.

**Comment by salikram** [comment]
0
down vote
favorite
I am using microsoft emotion api c# sdk. It was working good two days before, but It shows errors in VideoResultControl.xamp.cs today. I think Microsoft.ProjectOxford.Emotion is not installed properly. I don't understand whether this error occurs from my visual studio or from the NuGet package.

**Comment by brendanarnold** [comment]
@jasonvomsft @lightfrenzy Is there any updates on UWP support for Bing.Speech?

See https://cognitive.uservoice.com/forums/430321-bing-speech/suggestions/18440209-support-for-windows-10-uwp-in-bing-speech

**Comment by sveco** [comment]
I really do not understand this approach by Microsoft. Issue closed with no resolution. Is there any way to get the code, or is the suggestion that community writes client by itself as open source?
