### ISSUE TITLE
Domain Specific Model Call From VisionServiceRestClient Android Not Returning Celebrity Data

### ISSUE THREAD

**Issue by NotThatGupta** [Microsoft/ProjectOxford-ClientSDK#52]
When I call the AnalysisInDomainResult method from VisionServiceRestClient, I get the following response:

{"metadata":{"format":"Jpeg","height":450,"width":467},"requestId":"9ad8713b-93ce-4bcb-8bbe-723a88895559"}

Notice that no domain specific result is returned for the "celebrities" category string that I pass to the method. When I call the service directly without using the provided library (passing the same image url), I do get celebrity data back. With the library, I only get metadata and the requestId.

Is there an additional step to get the celebrity data from the service in the response?

Thanks in advance!

**Comment by chsienki** [comment]
Hi @NotThatGupta, 
This is a bug in the Android Client Library; a fix should be available shortly. Will let you as soon as it's up.

Thanks!

**Comment by chsienki** [comment]
This should be fixed as of  [vision 1.0.354](http://search.maven.org/#artifactdetails%7Ccom.microsoft.projectoxford%7Cvision%7C1.0.354%7Caar)

Let me know if you're still having issues.

**Comment by NotThatGupta** [comment]
Yup looks like it's fixed, thanks a lot!
