### ISSUE TITLE
Luis bug: end_time is returned as start_time

### ISSUE THREAD

**Issue by bluekite2000** [Microsoft/ProjectOxford-ClientSDK#53]
{
"query": "book me a room on 4/20 from 9am to 1pm",
"intents": [
{
"intent": "builtin.intent.calendar.create_calendar_entry"
}
],
"entities": [
{
"entity": "4/20",
"type": "builtin.calendar.start_date",
"resolution": {
"date": "XXXX-04-20",
"resolution_type": "builtin.datetime.date"
}
},
{
"entity": "9am",
"type": "builtin.calendar.start_time",
"resolution": {
"resolution_type": "builtin.datetime.time",
"time": "T09"
}
},
{
"entity": "1pm",
"type": "builtin.calendar.start_time",
"resolution": {
"resolution_type": "builtin.datetime.time",
"time": "T13"
}
}
]
}

**Comment by lightfrenzy** [comment]
Hi @bluekite2000,

For support questions, we can best help you through StackOverflow. 
I'm going to close out this issue and please post on our community if you still have this issue. Issues filed on this repo should be directly related to the SDKs within it.

Here's the link: https://stackoverflow.com/questions/tagged/microsoft-cognitive

Thanks!
