### ISSUE TITLE
start_date is mistake as end_date

### ISSUE THREAD

**Issue by bluekite2000** [Microsoft/ProjectOxford-ClientSDK#54]
When the query is  i want to book a room from 3pm to 4pm today
I get today as end_date
{
"query": "i want to book a room from 3pm to 4pm today",
"intents": [
{
"intent": "builtin.intent.calendar.create_calendar_entry"
}
],
"entities": [
{
"entity": "room",
"type": "builtin.calendar.title"
},
{
"entity": "3pm",
"type": "builtin.calendar.start_time",
"resolution": {
"resolution_type": "builtin.datetime.time",
"time": "T15"
}
},
{
"entity": "4pm",
"type": "builtin.calendar.end_time",
"resolution": {
"resolution_type": "builtin.datetime.time",
"time": "T16"
}
},
{
"entity": "today",
"type": "builtin.calendar.end_date",
"resolution": {
"date": "2016-04-20",
"resolution_type": "builtin.datetime.date"
}
}
]
}

**Comment by lightfrenzy** [comment]
Hi @bluekite2000,

For support questions, we can best help you through StackOverflow. 
I'm going to close out this issue and please post on our community if you still have this issue. Issues filed on this repo should be directly related to the SDKs within it.

Here's the link: https://stackoverflow.com/questions/tagged/microsoft-cognitive

Thanks!
