### ISSUE TITLE
LICENCE vs "can be used only pursuant to a non-disclosure agreement"

### ISSUE THREAD

**Issue by eadz** [Microsoft/ProjectOxford-ClientSDK#55]
The LICENCE file (MIT) conflicts with the header in speech.js

`// LICENSE
// -------
// © 2015 Microsoft. All rights reserved.  
// This document is provided “as-is”. Information and views expressed in this document, including URL and other Internet Web site references, may change without notice.  
// Some examples depicted herein are provided for illustration only and are fictitious.  No real association or connection is intended or should be inferred. 
// This document does not provide you with any legal rights to any intellectual property in any Microsoft product. You may copy and use this document for your internal, reference purposes. This 
// document is confidential and proprietary to Microsoft. It is disclosed and can be used only pursuant to a non-disclosure agreement. 
//----------------------------------------------------------------------
`

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-Speech-STT-JavaScript#5
