### ISSUE TITLE
Start date is missing 

### ISSUE THREAD

**Issue by bluekite2000** [Microsoft/ProjectOxford-ClientSDK#56]
When I enter book me a room today at 2pm, I get
{
"query": "book me a room today at 2pm",
"intents": [
{
"intent": "builtin.intent.calendar.create_calendar_entry"
}
],
"entities": [
{
"entity": "2pm",
"type": "builtin.calendar.start_time",
"resolution": {
"resolution_type": "builtin.datetime.time",
"time": "T14"
}
}
]
}v

**Comment by lightfrenzy** [comment]
Hi @bluekite2000,

For support questions, we can best help you through StackOverflow. 
I'm going to close out this issue and please post on our community if you still have this issue. Issues filed on this repo should be directly related to the SDKs within it.

Here's the link: https://stackoverflow.com/questions/tagged/microsoft-cognitive

Thanks!
