### ISSUE TITLE
RecognitionStatus "611" is not defined  in RecognitionStatus enum in SpeechClient.dll

### ISSUE THREAD

**Issue by abuzany** [Microsoft/ProjectOxford-ClientSDK#57]
When I sent an a audio file I get "611" in PhraseResponse.RecognitionStatus in "OnDataDictationResponseReceivedHandler"  but that status is  not  defined in n RecognitionStatus enum

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-Speech-STT-Windows#2
