### ISSUE TITLE
Using the Mac OSX SDK?

### ISSUE THREAD

**Issue by joacimstahl** [Microsoft/ProjectOxford-ClientSDK#59]
Trying to build an OSX app with the Mac OSX SDK SpeechSDK.framework, however the build fails with:

`/Contents/Frameworks/SpeechSDK.framework/Versions/A: No such file or directory
Command /usr/bin/codesign failed with exit code 1`

Any ideas?

**Comment by dmiller235623** [comment]
the privacy notice had me so freaked out.. I wont mess with it until I'm
guaranteed people are using these services legit... I envision holo lens

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-Speech-STT-iOS#2
