### ISSUE TITLE
a procedure imported by 'SpeachClient.dll' could not be loaded, on Windows 7

### ISSUE THREAD

**Issue by skalinkin** [Microsoft/ProjectOxford-ClientSDK#60]
I have build small app, it works on my box (Windows 10) I have copied Debug folder to my laptop for demo and got error above. see my project here https://github.com/skalinkin/PlayingWithSpeachToText
I have used nuget package but looks like missing some dependency

**Comment by bennettl** [comment]
Having the same issue, is the C# SDK not compatible with Windows 7?

**Comment by skalinkin** [comment]
What I figured out is Windows 7 is not supported.

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-Speech-STT-Windows#4
