### ISSUE TITLE
Speech.js should not call SpeechMain automatically

### ISSUE THREAD

**Issue by theluk** [Microsoft/ProjectOxford-ClientSDK#61]
In environments like node.js, loading the package causes errors, like window is undefined etc.

1. when loading the js sdk in a non-browser environment, errors should disapear. 
2. you should not access global vars (like `window`) but use instead `root` or similar.

the goal is to make the sdk more module-like #62

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-Speech-STT-JavaScript#6
