### ISSUE TITLE
NPM Package for Speech.js

### ISSUE THREAD

**Issue by theluk** [Microsoft/ProjectOxford-ClientSDK#62]
create a package.json and submit a package to the npm registry.

Required steps
1. The Speech.js should not access global variables like `window` or `navigator` #61 
2. The Speech.js should be wrapped in UMD factory pattern
3. The Speech.js should not call `SpeechMain()` automatically on load #61 
4. A package.json should be created and published to npm-registry

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-Speech-STT-JavaScript#7
