### ISSUE TITLE
iOS updated examples for Vision API

### ISSUE THREAD

**Issue by benmak11** [Microsoft/ProjectOxford-ClientSDK#63]
There currently is no app examples for the Vision API and I wanted to find out if that can be included within the next commit plans?

**Comment by lightfrenzy** [comment]
Hi @benmak11, great suggestion.

Can you actually post this on our UserVoice forum? That's where we are tracking asks for more SDKs and Samples: 

https://cognitive.uservoice.com/

I'm going to close this out, looking forward to seeing your ask on UserVoice so the community can vote on it and we can prioritize it on the team!
