### ISSUE TITLE
[Computer Vision Example][Python]Image and Result mismatch on local stored images

### ISSUE THREAD

**Issue by donnerz** [Microsoft/ProjectOxford-ClientSDK#64]
In the 'Analysis of an image stored on disk' section:
arr = np.asarray( bytearray( requests.get( urlImage ).content ), dtype=np.uint8 )
img = cv2.cvtColor( cv2.imdecode( arr, -1 ), cv2.COLOR_BGR2RGB )

The code above would fetch the online image in previous section again rather than the image stored locally. So the returned result of the local image would be rendered on the online image sample.

**Comment by cristiancanton** [comment]
Yes, that is right. A fix will be available soon. Thanks!

**Comment by mwinkle** [comment]
@cristiancanton was this fixed in b469c42 ?
