### ISSUE TITLE
C# Emotion SDK: Get ClientException without a message

### ISSUE THREAD

**Issue by SaqibS** [Microsoft/ProjectOxford-ClientSDK#7]
I integrated the Emotion Recognition SDK in my app, using the NuGet package. However, when I call EmotionServiceClient.RecognizeAsync(), I get a ClientException, without any message.

I tried the WPF sample in this repo, with various photos, and get the same problem - ClientException without a message. The photos are <4 MB and >35x35 pixels. They work with Face Detection.

**Comment by SaqibS** [comment]
Turns out this is related to the API key being used. However, this was hidden due to several reasons, which should ideally be rectified to avoid others going down this same path (happy to contribute a fix):

* The ClientException is wrapped inside an AggregateException (perhaps due to async/await? Don't know if this can be got around)
* The ClientException just has a generic message, saying that an exception was thrown (adds zero value); this is what the WPF sample prints out
* ClientException has a property, Error, which contains a Message and Code. I'd redesign this so that Code was a property of ClientException, and the actual ClientException.Message were populated.
* I notice this same pattern in the Face SDK.

**Comment by yungshinlintw** [comment]
Hi Saqib,
As we have discussed, we will improve the exception message here. Thanks again!

**Comment by cthrash** [comment]
Hi Saqib - new code was pushed out earlier that should address this issue.  Thank you for your patience.

**Comment by lightfrenzy** [comment]
Closing out since this is resolved in the latest update. Thanks for reporting @SaqibS!
