### ISSUE TITLE
Face API WPF samples

### ISSUE THREAD

**Issue by ShehabElDabaa** [Microsoft/ProjectOxford-ClientSDK#70]
can't build the solution.
project SampleUserControlLibrary is not loaded 

I searched for it in the folder isn't there

Found it but the solution still gives so many errors to build

**Comment by cthrash** [comment]
How did you clone the repo?   It's [here](https://github.com/Microsoft/ProjectOxford-ClientSDK/tree/master/SampleUtil/Windows/SampleUserControlLibrary).

**Comment by ShehabElDabaa** [comment]
Found it later. Thanks @cthrash
