### ISSUE TITLE
VideoServiceClient BadRequest when creating operation

### ISSUE THREAD

**Issue by theofanis** [Microsoft/ProjectOxford-ClientSDK#71]
I'm using video api version 1.0.1 from nuget.

When calling CreateOperationAsync with a videoUrl parameter and MotionDetectionOperationSettings I always get a bad request.

Observing the request using Fiddler the request is as follows (key and url are fake for this sample):

```
POST https://api.projectoxford.ai/video/v1.0/detectmotion HTTP/1.1
ocp-apim-subscription-key: xxxxxxxxxxxxxx
Content-Type: application/json; charset=utf-8
Host: api.projectoxford.ai
Content-Length: 55
Expect: 100-continue
Connection: Keep-Alive

"https://localhost:8888/videos/test.mp4"
```

This isn't a json payload.

**Comment by cthrash** [comment]
You are correct - that is a bug.
For now, instead of using `MotionDetectionOperationSettings`, call with `OperationType.DetectMotion` and it should work.  Ignore the 'obsolete' warning.

**Comment by theofanis** [comment]
I went with making the call using `HttpClient`, this was for a hackathon and needed a fast and dirty solution.

Thanks for your reply and excuse my late reply.

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-Video-Windows#2
