### ISSUE TITLE
FAILED to run the vision c# example

### ISSUE THREAD

**Issue by khadijah111** [Microsoft/ProjectOxford-ClientSDK#73]
hello every body.. 

i followed the steps written here 

https://www.microsoft.com/cognitive-services/en-us/computer-vision-api/documentation/getstarted/getstartedvisionapiforwindows

i downloaded the codes zip from gethups

1- the folder Sample-console not found

2- i tryied the examole inside SAMPLE.WPF and when tring to start the c# project, alot of errors generated like this:

Error CS0234
The type or namespace name 'ProjectOxford' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
VisionAPI-WPF-Samples C:\Users\khadijah\Documents\Visual Studio 2015\ProjectOxford-ClientSDK-CognitiveServices_1606\Vision\Windows\Sample-WPF\AnalyzeInDomainPage.xaml.cs
43 Active

do you have any idea please ..

thanks in advanced.

**Comment by cthrash** [comment]
For the first issue, as you've discovered, this is a documentation bug.  It should say Sample-WPF instead of Sample-Console.
For the second issue, you'll need to make sure the NuGet packages are downloaded.  If you're using Visual Studio 2015, you can right-click on the solution, and select "Restore NuGet Packages".  Alternatively, you can run "Nuget.exe restore" from the command line.

**Comment by khadijah111** [comment]
Thank you, yes i used 2015 , i tryed to restore NuGet packages, But the errors still appeared.!!!

**Comment by cthrash** [comment]
Can you go to Tools->NuGet Package Manager->Package Manager Console and try the following command: `Update-Package -Reinstall` ?  That should force the packages to get downloaded again.

**Comment by khadijah111** [comment]
thanks.
yes i did.
Now the errors decreased to 14 errors like:

CS0246	The type or namespace name 'SampleUserControlLibrary' could not be found (are you missing a using directive or an assembly reference?)	VisionAPI-WPF-Samples	C:\Users\khadijah\Documents\Visual Studio 2015\Vision\Windows\Sample-WPF\MainWindow.xaml

**Comment by cthrash** [comment]
Are you working with VisionAPI-WPF-Samples.sln (as opposed to VisionAPI-WPF-Samples.csproj)?  The solution should automatically include the dependent SampleUserControlLibrary project.

**Comment by khadijah111** [comment]
YES :) Now good. thank you .

only i have this, i think some thing i XML

Severity	Code	Description	Project	File	Line	Suppression State
Error		The tag 'SampleScenarios' does not exist in XML namespace 'clr-namespace:SampleUserControlLibrary;assembly=SampleUserControlLibrary'. Line 12 Position 10.	VisionAPI-WPF-Samples	C:\Users\khadijah\Documents\Visual Studio 2015\Vision\Windows\Sample-WPF\MainWindow.xaml	12

**Comment by khadijah111** [comment]
Thank you very much, you are save my time :+1:

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-Vision-Windows#3

**Comment by salikram** [comment]
I also have exactly same problem but still not solved

**Comment by lightfrenzy** [comment]
@salikram: Thanks for letting us know. You can continue following this issue in our new repo here: [https://github.com/Microsoft/Cognitive-Vision-Windows/issues/3](https://github.com/Microsoft/Cognitive-Vision-Windows/issues/3).

Let us know if you have any questions!
-Allison
