### ISSUE TITLE
SpeechToText-WPF-Sample Exception System.IO.FileLoadException

### ISSUE THREAD

**Issue by cywxer** [Microsoft/ProjectOxford-ClientSDK#74]
The example throw `System.IO.FileLoadException` when I do it as step and click the radio button.  I confirm that I import the `SpeechClient.dll`.

**Comment by kbpachauri** [comment]
I am also facing similar issue

**Comment by kbpachauri** [comment]
After upgrading my system from Window 7 to Windows 10, SpeechToText demo work perfectly fine.

**Comment by cywxer** [comment]
@kbpachauri thanks
