### ISSUE TITLE
How to increase Intial silence timeout

### ISSUE THREAD

**Issue by Jagadeesh-Govindaraj** [Microsoft/ProjectOxford-ClientSDK#76]
how can i incrase intial silence timeout in using speechreconizationservice factory

i did not see any property on this?

**Comment by Jagadeesh-Govindaraj** [comment]
Speechtotext Windows api

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-Speech-STT-Windows#5
