### ISSUE TITLE
Need to disable ASR when System speaks

### ISSUE THREAD

**Issue by sushma-ananda** [Microsoft/ProjectOxford-ClientSDK#77]
Right now when system speaks, OXford ASR takes user's speech as well system's spoken text (from TTS) and meddles up recognized result. Is there an option to detect echo and cancel or cancel barge-in ?

**Comment by lightfrenzy** [comment]
We do not have an option to detect echo and cancel today, but if you're interested in this feature, I highly recommend you file it as a feature request on our UserVoice site:

[http://cognitive.uservoice.com](http://cognitive.uservoice.com)

We are always looking for feature suggestions and if you file an idea on our site, you'll be updated if we have updates to share.
