### ISSUE TITLE
AndroidSDK doesn't work on Marshmallow

### ISSUE THREAD

**Issue by halissonvit** [Microsoft/ProjectOxford-ClientSDK#8]
I have been able to run the demo on other versions of android. 
When I attempt to run the demo on a 6.0 device, I get an error toast message and the following output log:

```
11-25 11:11:08.190 23946-25068/com.microsoft.AzureIntelligentServicesExample I/NLPLAT: ProcessMessageFailure@297 Message: 'S' has -1421792596 remaining transmit attempts.
11-25 11:11:08.190 23946-25068/com.microsoft.AzureIntelligentServicesExample I/NLPLAT: ProcessMessageFailure@302 Discarding failed message (name='S')
11-25 11:11:08.190 23946-25068/com.microsoft.AzureIntelligentServicesExample I/NLPLAT: NotifyMessageFailed@250 Reporting message failure to the observer (name='S')
11-25 11:11:08.190 23946-25068/com.microsoft.AzureIntelligentServicesExample I/NLPLAT: OnSendMessageFailed@248 Failed to 'hr', HR=8E200002, Failed to send message (name='S')
11-25 11:11:08.190 23946-25068/com.microsoft.AzureIntelligentServicesExample I/NLPLAT: ProcessTransportError@612 Transport error, hr=8E200002
11-25 11:11:08.190 23946-25068/com.microsoft.AzureIntelligentServicesExample E/NLPLAT: native error -1910505470
```

**Comment by yungshinlintw** [comment]
Thanks for the report. We will look into this.

**Comment by dlfu** [comment]
Hi @halissonvit !
Marshmallow has implemented a new way of handling permissions. Every time the app needs access to resources that might compromise privacy, the app has to verify that the permission is granted and if not ask for permission. The sample apps are not set up for that new system.

For now, if you want to try the demo on 6.0 device, go into the `build.gradle` file, change the `targetSdkVersion` to 22 and rebuild. It should make the app use the old permission system.

Let us know how it goes :) !

**Comment by halissonvit** [comment]
@dlfu thanks for your answer.

But I still get the same error after changing the targetSdkVersion.

```
2-02 18:22:19.741 17492-18976/com.microsoft.AzureIntelligentServicesExample I/NLPLAT: ProcessMessageFailure@302 Discarding failed message (name='S')
12-02 18:22:19.741 17492-18976/com.microsoft.AzureIntelligentServicesExample I/NLPLAT: NotifyMessageFailed@250 Reporting message failure to the observer (name='S')
12-02 18:22:19.741 17492-18976/com.microsoft.AzureIntelligentServicesExample I/NLPLAT: OnSendMessageFailed@248 Failed to 'hr', HR=8E200002, Failed to send message (name='S')
12-02 18:22:19.741 17492-18976/com.microsoft.AzureIntelligentServicesExample I/NLPLAT: ProcessTransportError@612 Transport error, hr=8E200002
12-02 18:22:19.742 17492-18976/com.microsoft.AzureIntelligentServicesExample E/NLPLAT: native error -1910505470
```

**Comment by dlfu** [comment]
Im sorry to hear that @halissonvit will report this to the platform devs to get a better sense of what that error is

**Comment by jasonvomsft** [comment]
8E200002 errors mean that authentication has failed.  Could you verify that your subscription keys are properly passed to the Speech API?

**Comment by halissonvit** [comment]
@jasonvomsft Thanks for the answer.

The subscriptions keys are okay and properly set up.
I use them in another project with Android 5.x, So I believe that is not the case.

**Comment by yungshinlintw** [comment]
I will be actively looking into this.

**Comment by yungshinlintw** [comment]
@halissonvit:
Sorry for getting back to you late on this. I cannot repro this issue from our side with Nexus phones with Marshmallow when running the demo, unfortunately. 

With that said, when the subscription ID is changed, I got the same error as 8e200002 (or -1910505470) error, so this is still like an subscription ID issue. 

Can you please double check on the following:
- When you run SpeechRecoSample, make sure that you go to strings.xml file and enter your subscription key. Please note that you need to update the value of "subscription_key" (the "Please_add_the_subscription_key_here" message), instead of the key itself or the value of "add_subscription_key_tip_title". This is a bit confusing.

<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools" tools:ignore="TypographyDashes">
    
    
    <string name="subscription_key">Please_add_the_subscription_key_here</string>

    <string name="add_subscription_key_tip_title">Subscription Key is Needed</string>

- If this still does not work, can you please go to http://projectoxford.ai and try to get a new key for speech? Please note that different technologies (speech, computer vision) all have different keys.

Thanks.

**Comment by halissonvit** [comment]
Hi @yungshinlintw . Thanks a lot for the answer. 
Sorry taking so long to answer, but we have been working on the ios app, and just now we could come back to this issue.

I have set up the keys correctly... It does work in android 5.0, but doesn't work on android 6.0.
I will try to reset the subscription key asap, I can't do right now because the current app is currently in prod.

**Comment by haluky** [comment]
i wonder is there will be Xamarin support?






















 



 


  | Haluk YILMAZ | +90 507 044 3 888 | FrontEnd Developer & IT Specialist |  
  Windows Phone HQ: http://goo.gl/RpG9Q    Android HQ: http://goo.gl/BJGQO
tr.linkedin.com/in/mustafahalukyilmaz/

Date: Mon, 11 Jan 2016 14:16:32 -0800

**Comment by lightfrenzy** [comment]
@halissonvit -- are you still having issues with this?

**Comment by halissonvit** [comment]
It works for me. 
Should have closed this, sorry.

Thank you for the help.
