### ISSUE TITLE
Pure Java libraries?

### ISSUE THREAD

**Issue by m-moris** [Microsoft/ProjectOxford-ClientSDK#80]
Do you have plan to release Pure Java libraries? If it is compiled in Pure Java, I think it will work fine.

**Comment by lightfrenzy** [comment]
We do not have any pure java libraries today, but if you're interested in this feature, I highly recommend you file it as a feature request on our UserVoice site:

[http://cognitive.uservoice.com](http://cognitive.uservoice.com)

We are always looking for feature suggestions and if you file an idea on our site, you'll be updated if we have updates to share.
