### ISSUE TITLE
error CS1061: 'DataRecognitionClient' does not contain a definition for 'WaitForFinalResponse' and no extension method 'WaitForFinalResponse'

### ISSUE THREAD

**Issue by kbpachauri** [Microsoft/ProjectOxford-ClientSDK#82]
I am trying to call WaitForFinalResponse, but getting error, According to sdk documentation, this method is supported (https://staging.www.projectoxford.ai/Files/Doc/Speech/Windows/html/ff4169e5-6142-558a-92af-48618f592f39.htm)
this.dataClient.WaitForFinalResponse();
kindly help. Thanks

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-Speech-STT-Windows#6
