### ISSUE TITLE
Moved why Project

### ISSUE THREAD

**Issue by mesutpiskin** [Microsoft/ProjectOxford-ClientSDK#88]
Moved why this project? Will it continue development ??

**Comment by lightfrenzy** [comment]
Hi @mesutpiskin. Yes, we are continuing the development of all the projects. Previously, there were 20+ solutions within this repo, which made development extremely difficult. If I wanted to work with the Android SDK for the Emotion API, I would need to pull ALL of the projects for ALL of the APIs. This problem will only get worse with time as we continue to develop Cognitive Services and increase our SDK coverage.

As such, we simply moved the projects into their own repo. You can find all the new links here: [https://www.microsoft.com/cognitive-services/en-us/SDK-Sample](https://www.microsoft.com/cognitive-services/en-us/SDK-Sample). 

Let me know if you have any questions!
-Allison

**Comment by mesutpiskin** [comment]
Thank you so much for answer. We love Microsoft and open source :)
