### ISSUE TITLE
Including .wav file in Identification Profile Enrollment request via Ruby

### ISSUE THREAD

**Issue by jgujgu** [Microsoft/ProjectOxford-ClientSDK#89]
Hello,

I've been reading through the documentation for [Speaker Recognition API]( https://dev.projectoxford.ai/docs/services/563309b6778daf02acc0a508/operations/5645c3271984551c84ec6797) and apologize in advance for bothering you on Github, but I've been having somewhat of a hard time figuring out how to include a `.wav` file in the example code provided, where it is simply listed as `"{body}"`:

```ruby
require 'net/http'

uri = URI('https://api.projectoxford.ai/spid/v1.0/identificationProfiles/{identificationProfileId}/enroll')
uri.query = URI.encode_www_form({
    # Request parameters
    'shortAudio' => '{boolean}'
})

request = Net::HTTP::Post.new(uri.request_uri)
# Request headers
request['Content-Type'] = 'multipart/form-data'
# Request headers
request['Ocp-Apim-Subscription-Key'] = '{subscription key}'
# Request body
request.body = "{body}"

response = Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|
    http.request(request)
end

puts response.body
```

I have attempted to use the `Faraday` gem to make things easier and have successfully posted to the Profile creation endpoint with it: 

```ruby
    url = 'https://api.projectoxford.ai/spid/v1.0/identificationProfiles'
    msft_request_body = {
      "locale":"en-us"
    }.to_json
    conn = Faraday.new(:url => url) do |faraday|
      faraday.request  :url_encoded             # form-encode POST params
      faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
    end

    msft_response = conn.post do |req|
      req.headers['Content-Type'] = 'application/json'
      req.headers['Ocp-Apim-Subscription-Key'] = ENV["MSFT_IDENTIFICATION_API_KEY"]
      req.body = msft_request_body
    end
```

`Faraday` provides a wrapper to send files, and I have used it successfully in the past to send audio files to an endpoint of my creation. Here is an example of how the code might look in this case:

```ruby
    identificationProfileId = "2e4bfbe1-683e-4e4e-99e2-db30061307ec"
    url = "https://api.projectoxford.ai/spid/v1.0/identificationProfiles/#{identificationProfileId}/enroll"

    conn = Faraday.new(:url => url ) do |c|
      c.request :multipart
      c.request :url_encoded
      c.adapter :net_http
    end
    file_path = Rails.root + "identification_profile.wav"
    content_type = "audio/wav"
    payload = Faraday::UploadIO.new(file_path, content_type)

    msft_response = conn.post do |req|
      #req.url url
      req.headers['Content-Type'] = 'multipart/form-data'
      req.headers['Ocp-Apim-Subscription-Key'] = ENV["MSFT_IDENTIFICATION_API_KEY"]
      req.params = { identificationProfileId: identificationProfileId }
      req.body = payload
     end
```

However, this does not create a successful response from the API. Would you be able to provide an example, using `Faraday` or `Net::HTTP` showing how to attach the `.wav` file?

-Jeffrey

**Comment by momohs** [comment]
Thank you @jgujgu for your comment! We will look into it.

**Comment by jgujgu** [comment]
Hi @momohs,

I ended up having success with the method I mention in [this comment](https://github.com/Microsoft/Cognitive-Documentation/issues/56). I made an issue there because I thought it was the more up to date repo. Thank you for getting back.

-Jeffrey
