### ISSUE TITLE
Unclear API usage

### ISSUE THREAD

**Issue by StenPetrov** [Microsoft/ProjectOxford-ClientSDK#9]
I'm not clear on what the right sequence for using the API is. 

My scenario is using the Face API for logging into an app.

The app starts with no users, the first user that's recognized should be added to a new group. 
After that when a new user's face isn't recognized with sufficient confidence a new user is registered in the same group. 
If an user is recognized the new face ID is added to the person's object and if there are more than 32 IDs the oldest is dropped.

(1) I saw somewhere the face IDs expire. How long do they live?
(2) what are the sequences of calls to make to the API,
(3) what is a "sufficient confidence"
(4) do I need to store images locally?

**Comment by Terryzcx** [comment]
1. face id expires 24 hours after it is being detected.

2. the basic flow is:
The app starts with no users, 
[create a empty person group] -> [list persons in a person group] count == 0
the first user that's recognized should be added to a new group. 
[add person to person group]
 After that when a new user's face isn't recognized with sufficient confidence a new user is registered in the same group. 
[add person to person group]
 If an user is recognized the new face ID is added to the person's object and if there are more than 32 IDs the oldest is dropped.
[add face to person][delete face from person].
[one thing to mention is, you need to retrain a person group if you made any change to its persons/faces before it takes effects in identification API.]

3. when an user is identified by the identification API, it is already sufficient from our side. the confidence is used only when you need to judge base on your own criteria. 

4. it is up to your own logic to decide whether you need to storage the image locally. we don't need it once it is detected using the Detection API.

**Comment by StenPetrov** [comment]
if face IDs expire in 24h does that mean the group also expires in 24h because all the face IDs associated with people in it are gone? Will I be able to log in a user returning after more than 24h?

**Comment by Terryzcx** [comment]
Person group will not expire unless you manually delete it.

If you add the face ID into a person, you can use it for ever unless you delete it manually. But just note, after expiration, you can only use that face ID in the person related scopes, like person group related APIs/train a person group API/identify API, you cannot use it for verification/grouping/find similar purposes.

**Comment by lightfrenzy** [comment]
Closing out the issue since the question has been answered. @StenPetrov feel free to reopen if you have any further questions!
