### ISSUE TITLE
" API call threw an Exception"

### ISSUE THREAD

**Issue by Almaas** [Microsoft/ProjectOxford-ClientSDK#91]
Hi
I am running the Basic Console Sample( C#), I have built the project with no errors. Although new frames/faces are acquired and submitted. There is the following error  on the console " API call threw and Exception".
 I have already entered the Face API Key to the Program.cs file. 

Any idea of what I might be doing wrong?

**Comment by lightfrenzy** [comment]
Hi @Almaas,

It sounds like you're trying to use the C# sample for the Face API, correct? A few months ago, we broke out each project in this repo into separate repos. As such, the new repo for Face can be found here: [https://github.com/Microsoft/cognitive-face-windows](https://github.com/Microsoft/cognitive-face-windows).

We have made updates to the Face-Windows repo over the past few months. I would start by pulling the latest code, inserting your API key, and seeing if you can run it without errors. If you still run into an issue, feel free to reach out on StackOverflow: [https://stackoverflow.com/questions/tagged/microsoft-cognitive](https://stackoverflow.com/questions/tagged/microsoft-cognitive).

Thanks!
