### ISSUE TITLE
"message": "Invalid Audio Format: Not a WAVE file - no RIFF header"

### ISSUE THREAD

**Issue by Crasheng** [Microsoft/ProjectOxford-ClientSDK#92]
"message": "Invalid Audio Format: Not a WAVE file - no RIFF header"
"message": "Invalid Audio Format: Not a WAVE file - no RIFF header"

I am Overwhelmed really,

I am trying hard to identify what is the problem and i do not know.

I have used the sample code in Python to make an enrollment, and it succeeded!!
but when it comes to Android, i stay now for 3 days try to figure out the issue and i am not able to know.

`   

     @Headers({"Ocp-Apim-Subscription-Key: insertAPIkEYHERE", "Content-Type: multipart/form-data"})
     @Multipart
     @POST("identificationProfiles/{identificationProfileId}/enroll")
     Call<ResponseBody> createEnrollment(
            @Path("identificationProfileId") String profileId,
            @Part MultipartBody.Part audiofile);`

`
       File file = new File(filePath);
       RequestBody requestFile = RequestBody.create(MediaType.parse("multipart/form-data"), file);
       MultipartBody.Part body =
                MultipartBody.Part.createFormData("uploaded_file", file.getName(), requestFile);
  
        Call<ResponseBody> response = clientRest.createEnrollment(profile_id, body);
`
I am overwhelmed

**Comment by momohs** [comment]
Moved to correct repo: https://github.com/Microsoft/Cognitive-SpeakerRecognition-Android/issues/2

**Comment by bernardomesk** [comment]
@Crasheng did you menage to work? I am having the same problem using Retrofit 2 and still nothing!
